apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: strongmariadbpassword
            - name: MYSQL_DATABASE
              value: my-expenses
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: mariadb-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-expenses
spec:
  selector:
    app: my-expenses
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-expenses
spec:
  selector:
    matchLabels:
      app: my-expenses
  replicas: 1
  template:
    metadata:
      labels:
        app: my-expenses
    spec:
      containers:
        - name: my-expenses
          image: aminaleahmad/my-expenses:latest
          env:
            - name: DB_HOST
              value: mariadb
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: strongmariadbpassword
            - name: DB_DATABASE
              value: my-expenses
            - name: DB_TABLE_NAME
              value: my-expenses
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi